### ISSUE TITLE
Are the actuated traffic lights really actuated?

### ISSUE THREAD

**Issue by gustavnilsson** [lcodeca/LuSTScenario#4]
First of all, thanks for great work with building up a realistic scenario. It is really appreciated. 

I have one question regarding the actuated traffic lights: It seems like the phases do not have minDur and maxDur attributes in the lust.net.xml file. Instead, the phases just have the duration attribute (that is different from tll.static.xml, so the "actuated" simulations will yield different results anyway), and hence the traffic signals will not behave like actuated according to the documentation (http://sumo.dlr.de/wiki/Simulation/Traffic_Lights#Based_on_Time_Gaps).

Can it have something to do with this bug? https://sourceforge.net/p/sumo/mailman/message/35513637/
Or have I misunderstood something?

Best regards,
Gustav

**Comment by lcodeca** [comment]
I just checked and you are right, there is something wrong with the actuated TLS. 
Unfortunately, I don't have access to the raw data anymore, and I'm not actively working on this project since 2017. I'm not going to fix them for a simulator that is outdated.
In case you want to fix them, this scenario is for SUMO 0.26, so I'm not sure if the wiki page you are using is the correct one. Many things have changed in the last ~3 years.

If you need a scenario that is in active development and works with the latest SUMO, you should check https://github.com/lcodeca/MoSTScenario
