### ISSUE TITLE
Very big gridlock in static DUE scenario (using SUMO 0.32)

### ISSUE THREAD

**Issue by beedrill** [lcodeca/LuSTScenario#5]
I observe huge gridlock in this scenario, by running 
sumo -c due.static.sumocfg

This makes the whole scenario unreal.
Is there a way to fix it?

**Comment by thardes2** [comment]
Hi,

which version of SUMO are you using? The problem shouldn't appear with SUMO 0.26.

Regards,

**Comment by beedrill** [comment]
I am using 0.32, but I really don't think the version of SUMO can change the performance. 
The gridlock only show up at late stage (40000+s) and only show up on a particular part of the map (several streets on south-east,  for example), please refer to the snapshot in attached:
![screenshot from 2018-11-06 00-53-59](https://user-images.githubusercontent.com/9779752/48045536-b5519c00-e15e-11e8-8e98-551c88284b85.png)

I observe this under DUE-static scenario.

**Comment by lcodeca** [comment]
DUE stands for Dynamic User Equilibrium and is generated running 50+ cycles of simulations with SUMO 0.26. It's expected that changing the simulator, the equilibrium is gone. If you use it with another version of sumo, the traffic demand is not validated anymore.

**Comment by beedrill** [comment]
Thank you, by changing to version 0.26.0, I do see the problem disappear. There is no cars teleporting anymore. 

I still don't understand that since the route file is generated after running duaIterate. Namely, the route file you included should be the one that already achieved equilibrium, how is changing SUMO version makes difference?

Meanwhile, is there a way to have it work for SUMO 0.32?

**Comment by lcodeca** [comment]
It's not only a matter of routes, from 0.26 to 0.32 (or newer) the mobility model has changed (improved) and the interactions between vehicles are not the same anymore. 
I don't have access to the validation data since I finished the PhD, so no, I cannot update this project.
I don't know what are you doing with this scenario, but if you need a scenario with an up-to-date version of SUMO, check [https://github.com/lcodeca/MoSTScenario](https://github.com/lcodeca/MoSTScenario )
