### ISSUE TITLE
configuration files are incompatible with sumo version >= 1.0.0

### ISSUE THREAD

**Issue by namdre** [lcodeca/LuSTScenario#8]
Since 1.1.0 spaces are no longer allowed as file path separator and ',' must be used.
It would be great if LuST could be used with a recent sumo.

**Comment by lcodeca** [comment]
The long answer on why I didn't do it on purpose is here: https://github.com/lcodeca/LuSTScenario/pull/6

You are not the only one that asked so now I did it, but the problem is more complicated. 
LuST Scenario has been validated with SUMO 0.26 and if you use another version, the traffic demand cannot be considered validated anymore. 
For this reason, I added the disclaimer in the README: 
"_LuST Scenario has been generated with SUMO version 0.26 and validated with real data. Although it's possible to use it with more recent versions of SUMO, the resulting mobility cannot be considered validated._"

I already saw some people using it in the wrong way, I just wanted to avoid the problem in the first place.

**Comment by namdre** [comment]
Thanks for the fix and explanation.  It think it would be worthwhile to have a compatible LuST scenario rather then letting it disappear into history.  Wouldn't it be possible to validate an updated scenario against the traffic data from the old scenario? Of course, this is not as good as validation against the ground truth but at least one could avoid major behavioral divergence.

**Comment by lcodeca** [comment]
Yes, it would be possible, but it's not going to be fast nor easy. 
I already tried to do it for 0.32.0 on my spare time a while ago and it was cumbersome: changes in the net, and both the device rerouter and the DUAIterate scripts were giving very different results from what I had.
Now I'm actively maintaining https://github.com/lcodeca/MoSTScenario to be up-to-date with the latest SUMO developments.
I don't want LuSTScenario to be forgotten, but how things are now and with all the (amazing) changes in SUMO, it would almost be easier starting from scratch and overlooking the proper validation with real data than fixing it.
